# This file was generated by GoReleaser. DO NOT EDIT.
cask "csaw" do
  version "0.3.0"

  on_macos do
    on_intel do
      url "https://github.com/csaw-ai/csaw/releases/download/v#{version}/csaw_#{version}_darwin_amd64.tar.gz"
      sha256 "3ee4d99730876239601fc59bc0c5cfba584b47c30dff1ada48073f684cad54dc"
    end
    on_arm do
      url "https://github.com/csaw-ai/csaw/releases/download/v#{version}/csaw_#{version}_darwin_arm64.tar.gz"
      sha256 "9efe1f47e01c6d050dad891b9d6b06f5388aa5e196fc18d8b5d0da38df3c2d5c"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/csaw-ai/csaw/releases/download/v#{version}/csaw_#{version}_linux_amd64.tar.gz"
      sha256 "d99f28c3b768b9ca8a466ce60d7dbaf2aee9bae0ec51ee659dfb611aac1b1ca9"
    end
    on_arm do
      url "https://github.com/csaw-ai/csaw/releases/download/v#{version}/csaw_#{version}_linux_arm64.tar.gz"
      sha256 "e13f6dbb9d7b83e223f5fb123d18e0991c5e8fdd922ffe5dc317a3fe98658625"
    end
  end

  name "csaw"
  desc "Mount, not install. AI workspace configuration from git-backed registries."
  homepage "https://github.com/csaw-ai/csaw"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "csaw"

  # No zap stanza required

end
