# This file was generated by GoReleaser. DO NOT EDIT.
cask "csaw" do
  version "0.2.2"

  on_macos do
    on_intel do
      url "https://github.com/csaw-ai/csaw/releases/download/v#{version}/csaw_#{version}_darwin_amd64.tar.gz"
      sha256 "0659f4f4fead54bbd351120fa977717d4451d5c9aace98f0c01e652b4e69bac9"
    end
    on_arm do
      url "https://github.com/csaw-ai/csaw/releases/download/v#{version}/csaw_#{version}_darwin_arm64.tar.gz"
      sha256 "b30a0e4de0e3b0a40c86a7af5347fe0458439555f9503e5e77243771552685bb"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/csaw-ai/csaw/releases/download/v#{version}/csaw_#{version}_linux_amd64.tar.gz"
      sha256 "aa8cdc7b4c78d8fa1706ff2e6c8ba3e8548b49c564f01cdb29e68ca112b7b814"
    end
    on_arm do
      url "https://github.com/csaw-ai/csaw/releases/download/v#{version}/csaw_#{version}_linux_arm64.tar.gz"
      sha256 "c0392cbc7caee964a37501183c55ba5f918b1cf5d8eee0cf4a140e23c07603be"
    end
  end

  name "csaw"
  desc "Mount, not install. AI workspace configuration from git-backed registries."
  homepage "https://github.com/csaw-ai/csaw"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "csaw"

  # No zap stanza required

end
