# This file was generated by GoReleaser. DO NOT EDIT.
cask "csaw" do
  version "0.1.0"

  on_macos do
    on_intel do
      url "https://github.com/csaw-ai/csaw/releases/download/v#{version}/csaw_#{version}_darwin_amd64.tar.gz"
      sha256 "2b8f68d6d59681724e036cd1073e960cf04015a5d9c5f00b34aabb197c02875d"
    end
    on_arm do
      url "https://github.com/csaw-ai/csaw/releases/download/v#{version}/csaw_#{version}_darwin_arm64.tar.gz"
      sha256 "ad5885e326b8fb036d46ec4527eb4e24b8227d9368128212199f927cc387c7b0"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/csaw-ai/csaw/releases/download/v#{version}/csaw_#{version}_linux_amd64.tar.gz"
      sha256 "74782b5eb51b77ad2dd8f6dbdf9bb041dd95476e5380831d7d54d05f21d523c9"
    end
    on_arm do
      url "https://github.com/csaw-ai/csaw/releases/download/v#{version}/csaw_#{version}_linux_arm64.tar.gz"
      sha256 "2ad0f393576e399beddf1cba02ccf88c2e62afab56f7cb0f9b339fb2755c5565"
    end
  end

  name "csaw"
  desc "Mount, not install. AI workspace configuration from git-backed registries."
  homepage "https://github.com/csaw-ai/csaw"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "csaw"

  # No zap stanza required

end
